# Generated by Django 4.1.13 on 2024-09-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phoneNumber',
            field=models.BigIntegerField(default=91),
            preserve_default=False,
        ),
    ]
