# Generated by Django 4.1.13 on 2024-09-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_users_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('LeaveId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('LeaveDate', models.DateField()),
                ('Reason', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=500)),
                ('Manager', models.CharField(max_length=500)),
            ],
        )
    ]
