# Generated by Django 4.1.13 on 2024-09-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_leave_employees_manager_employees_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendanceId', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.AddField(
            model_name='employees',
            name='Manager',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AddField(
            model_name='employees',
            name='Role',
            field=models.CharField(default='undefined', max_length=500),
            preserve_default=False,
        ),
    ]
