# Generated by Django 4.1.13 on 2024-09-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_attendance_delete_leave_employees_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('LeaveId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=500)),
                ('LeaveDate', models.DateField()),
                ('Reason', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=500)),
                ('ReportingManager', models.CharField(max_length=500)),
            ],
        ),
    ]
