# Generated by Django 4.1.13 on 2024-09-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0006_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('ProjectId', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=500)),
                ('ReportingManager', models.CharField(max_length=500)),
                ('Origin', models.CharField(max_length=500)),
                ('StartedDate', models.DateField()),
                ('Requirements', models.CharField(max_length=500)),
            ],
        ),
    ]
