# Generated by Django 4.1.13 on 2024-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0007_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='WorkingEmployeeIds',
            field=models.JSONField(default=list),
        ),
    ]
