# Generated by Django 4.1.13 on 2024-10-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0008_projects_workingemployeeids'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='ProjectId',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
