# Generated by Django 4.1.13 on 2024-10-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0009_employees_projectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Email',
            field=models.CharField(default='undefined', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='Password',
            field=models.CharField(default='undefined', max_length=500),
            preserve_default=False,
        ),
    ]
