# Generated by Django 4.1.13 on 2024-10-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0010_employees_email_employees_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='PhotoFileName',
        ),
    ]
