# Generated by Django 4.1.13 on 2024-11-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0011_remove_employees_photofilename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeeId',
            new_name='id',
        ),
    ]
